apiVersion: v1
kind: Pod
metadata:
  name: build-python-backend
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://github.com/GSA-COMET-Technical-Challenge/python-microservice-template"
    - "--destination=rivagsacomettechchal/python-microservice-template:latest"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: comet-dockerhub-cred
      items:
        - key: .dockerconfigjson
          path: config.json
